### ISSUE TITLE
GeneStatistics Roadmap

### ISSUE THREAD

**Issue by iQuxLE** [iQuxLE/acmgExomiser#6]
__________WITHOUT JANNOVAR__________
(but could annotate later on after getting from mvStore, only if needed, but bf makes no sense, if we do early computed only one time and correctly and we have the ready to serve map instead manipulating to be ready later on and having only half useful data in store)

- [ ] implement GeneStatsDataBaseBuildRunner
- [x] implement ClinVarGeneStatistics
- [ ] update MvStoreUtil
- [x] implement GeneStatsDao
- [x] implement GeneStatsDaoMvStore
- [x] update Allele.Proto
- [ ] implement GeneStatsVcfParser
- [x] modify VariantDataService

___________WITH JANNOVAR___________

Molecular Consequence Annotation with Jannovar:
- [ ] Use Jannovar to annotate the molecular consequence for each variant.
- [ ] Update the ExtendedAllele objects with the annotated molecular consequence.

ExtendedAllele Subclass:
- [ ] Create a subclass ExtendedAllele that extends Allele.
- [ ] Add additional fields for geneSymbol and clinSig in ExtendedAllele.
- [ ] Use VariantAnnotator to populate geneSymbol and molecular consequence fields in ExtendedAllele.
- [ ] Update ExtendedAllele objects with clinicalSignificance from ClinVarData based on alleleID.

MVStore Integration:
- [ ] Define a unique identifier (AlleleID) for each ExtendedAllele object.
- [ ] Store ExtendedAllele objects in the MVStore using AlleleID (or the whole AlleleKey object?) as the key.
- [ ] Implement a mechanism to retrieve GeneStatistics from MVStore using AlleleID/AlleleKey.
- [ ] Update GeneStatistics with data from ExtendedAllele.

Data Association:
- [ ] After both ClinVarData and ExtendedAllele objects are stored, associate them via alleleID.

Testing and Validation:
- [ ] Write unit tests to confirm that all components are working as expected.
- [ ] Validate the workflow with real-world data.
